- name: Install packages
  apt:
    name:
      - terminator
      - git
      - openvpn
      - keepassxc
      - thunderbird
      - teamviewer
      - tmux
      - vlc
    state: latest

- name: Install cloudflared
  get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
    dest: /usr/local/bin/cloudflared
    mode: 777

- name: Copy SSH config
  copy:
    src: "{{ role_path }}/files/.ssh"
    dest: "{{ home }}"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Set GIT email
  community.general.git_config:
    name: user.email
    scope: global
    value: "martin@balko.info"

- name: Set GIT name
  community.general.git_config:
    name: user.name
    scope: global
    value: "Martin Balko"

#- import_tasks: syncthing.yaml